<a href="https://colab.research.google.com/github/SlaveWilson/tensorflow/blob/main/Module_2_Introduction_to_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 2 - Introduction to TensorFlow

---



## What can we do with TensorFlow

- Image Classification
- Data Clustering
- Regression
- Reiforcement Learning
- Natural Langugage Processing

## How does it work

- Two main components
 - Graphs
 - Sessions

## Installing TensorFlow


In [ ]:
pip install tensorflow

If you want to use CUDA gpu

In [ ]:
pip install tensorflow-gpu

## Importing TensorFlow



In [40]:
%tensorflow_version 2.x # this line is not required unless you are in a notebook 

`%tensorflow_version` only switches the major version: 1.x or 2.x.
You set: `2.x # this line is not required unless you are in a notebook`. This will be interpreted as: `2.x`.


TensorFlow is already loaded. Please restart the runtime to change versions.


In [41]:
import tensorflow as tf # now import the tensorflow module
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## Tensors

- A vector generalized to higher dimensions
- Each tensor represents a partialy defined computation that will eventually produce a value

Each tensor has a **data type** and a **shape**
- **Data Types Include**: float32, int32, string and others
- **Shape**: Represents the dimension of data

## Creating Tensors

In [6]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567,tf.float64)

## Rank/Degree of Tensors

- Scalar: scalar value means 1 value
- Vector: vector value means more than 1 value

To create some tensors of higher degrees/ranks

In [15]:
rank1_tensor = tf.Variable(["Test", "Ok", "Tim"], tf.string)
rank2_tensor = tf.Variable([["test","ok","asd"],["test","yes","asd"]], tf.string)

To determine the rank of a tensor

In [16]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

## Shape of Tensors

- How many items we have in each dimension

To get the shape of a tensor

In [19]:
rank2_tensor.shape

TensorShape([2, 3])

## Changing Shape

- 

To Change the shape of a tensor

In [37]:
tensor1 = tf.ones([1,2,4])
tensor2 = tf.reshape(tensor1, [2,2,2])
tensor3 = tf.reshape(tensor2, [4,-1]) # -1 tells the tensor to calculate the size of the dimension in that place

In [38]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(1, 2, 4), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(2, 2, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]], shape=(4, 2), dtype=float32)


## Types of Tensors

- Variable (Important)
 - Mutable
- Constant (Important)
 - Immutable
- Placeholder
- SparseTensor



## Evaluating Tensors

- The only way to evaluate the tensors is to create a session

Simplest way:

In [ ]:
with tf.Session() as sess: # creates a session using the default graph
  tensor.eval() # tensor will of course be the name of your tensor

## Sources

https://www.tensorflow.org/guide/tensor

---



## Exercise

In [50]:
t = tf.zeros([5,5,5,5])
t = tf.reshape(t, [125, -1])
print(t)

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]